config/routes.rb
Rails.application.routes.draw do
  resources :raticles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/raticle.rb
class Raticle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/raticles_controller.rb
class RaticlesController < ApplicationController
  before_action :set_raticle, only: [:show, :edit, :update, :destroy]

  # GET /raticles
  # GET /raticles.json
  def index
    @raticles = Raticle.all
  end

  # GET /raticles/1
  # GET /raticles/1.json
  def show
  end

  # GET /raticles/new
  def new
    @raticle = Raticle.new
  end

  # GET /raticles/1/edit
  def edit
  end

  # POST /raticles
  # POST /raticles.json
  def create
    @raticle = Raticle.new(raticle_params)

    respond_to do |format|
      if @raticle.save
        format.html { redirect_to @raticle, notice: 'Raticle was successfully created.' }
        format.json { render :show, status: :created, location: @raticle }
      else
        format.html { render :new }
        format.json { render json: @raticle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raticles/1
  # PATCH/PUT /raticles/1.json
  def update
    respond_to do |format|
      if @raticle.update(raticle_params)
        format.html { redirect_to @raticle, notice: 'Raticle was successfully updated.' }
        format.json { render :show, status: :ok, location: @raticle }
      else
        format.html { render :edit }
        format.json { render json: @raticle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raticles/1
  # DELETE /raticles/1.json
  def destroy
    @raticle.destroy
    respond_to do |format|
      format.html { redirect_to raticles_url, notice: 'Raticle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raticle
      @raticle = Raticle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def raticle_params
      params.require(:raticle).permit(:title, :author, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/raticles_helper.rb
module RaticlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/raticles/_form.html.erb
<%= form_with(model: raticle, local: true) do |form| %>
  <% if raticle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(raticle.errors.count, "error") %> prohibited this raticle from being saved:</h2>

      <ul>
        <% raticle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/raticles/edit.html.erb
<h1>Editing Raticle</h1>

<%= render 'form', raticle: @raticle %>

<%= link_to 'Show', @raticle %> |
<%= link_to 'Back', raticles_path %>

app/views/raticles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Raticles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @raticles.each do |raticle| %>
      <tr>
        <td><%= raticle.title %></td>
        <td><%= raticle.author %></td>
        <td><%= raticle.text %></td>
        <td><%= link_to 'Show', raticle %></td>
        <td><%= link_to 'Edit', edit_raticle_path(raticle) %></td>
        <td><%= link_to 'Destroy', raticle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Raticle', new_raticle_path %>

app/views/raticles/new.html.erb
<h1>New Raticle</h1>

<%= render 'form', raticle: @raticle %>

<%= link_to 'Back', raticles_path %>

app/views/raticles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @raticle.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @raticle.author %>
</p>

<p>
  <strong>Text:</strong>
  <%= @raticle.text %>
</p>

<%= link_to 'Edit', edit_raticle_path(@raticle) %> |
<%= link_to 'Back', raticles_path %>